version: '3.9'

services:

  fit-database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: fit-database
    restart: always
    tty: true
    volumes:
      - "./mysql/:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ''
      MYSQL_RANDOM_ROOT_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'fit'
    ports:
      - "3306:3306"

  fit-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fit-api
    working_dir: /var/www/
    tty: true
    depends_on:
      - fit-database
    ports:
      - "8099:8000"
    volumes:
      - "./api/:/var/www/"

networks:
  default:
    name: fit_default